//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Cust_id { get; set; }
        public string Cust_Name { get; set; }
        public string Cust_Address { get; set; }
    }
}
