//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesNew
    {
        public int E_id { get; set; }
        public string E_name { get; set; }
        public Nullable<int> Sal { get; set; }
        public string E_address { get; set; }
    }
}
